//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteBackup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class BackupProfileRepository : global::System.Configuration.ApplicationSettingsBase {
        
        private static BackupProfileRepository defaultInstance = ((BackupProfileRepository)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BackupProfileRepository())));
        
        public static BackupProfileRepository Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ObjectModel.ObservableCollection<CompleteBackup.Models.Backup.Profile.BackupProfileData> BackupProfileList {
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<CompleteBackup.Models.Backup.Profile.BackupProfileData>)(this["BackupProfileList"]));
            }
            set {
                this["BackupProfileList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
